name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
      - Owen-reactstuff

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2  

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install gcloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1
        with:
          project_id: CS1660-FinalProj
          service_account_email: cs1660-finalproj@appspot.gserviceaccount.com
          export_default_credentials: true

      - name: Install dependencies and build
        run: |
          cd cs1660final-react
          npm install
          npm run build

      - name: Deploy to App Engine
        run: |
          gcloud app deploy app.yaml --quiet --version=main
