name: CI

on:
  push:
    branches:
      - Owen-reactstuff  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v2  

      - name: Install dependencies  
        run: |
          cd cs1660final-react
          npm install  

      - name: Build  
        run: |
          cd cs1660final-react
          npm run build  
